### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-buriak#2]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
1) Відомо, що безпечна клієнт-серверна взаємодія може забезпечуватися через наступні ключи: 
відкритий ключ клієнта, закритий ключ клієнта, відкритий ключ сервера, закритий ключ сервера. 
Вкажіть, будь ласка, який ключ вами було використано під час налаштування безпечного оновлення 
GitHub-репозиторію змінами з локального Git-репозиторію.

**Comment by Yakiv7** [comment]
Для налаштування безпечного оновлення github-репозиторію змінами з локального git-репозиторію, буде використаний відкритий ключ сервера. Приклад роботи даного механізму такий:

1. Користувач створює зміни у своєму локальному git-репозиторії.
2. Користувач відправляє команду на оновлення репозиторію на GitHub сервер, передаючи свій публічний ключ сервера.
3. GitHub сервер перевіряє, чи існує цей публічний ключ на їх сервері та чи користувач має дозвіл на зміни в репозиторії.
4. Якщо перевірка вдалася, сервер дозволяє оновлення репозиторію змінами з локального git-репозиторію.

Такий механізм забезпечує безпеку та контроль доступу до репозиторію на GitHub. Він дозволяє виключити можливість несанкціонованого оновлення репозиторію та зберігати дані безпечно.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
